Author.create!([
  {name: "Maestro", username: "jlsodai", email: "jlsodai@gmail.com", bio: "I am an entrepreneur and also love to cook", expertise: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, password_digest: "$2a$10$niIr4ZMcFPyaZmtHHrBfW.oyS2aY7FQ8xgapkcG4.jXKPKryiV59W", remember_digest: nil, admin: true},
  {name: "Amanze", username: "amanze", email: "amanze@gmail.com", bio: "", expertise: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, password_digest: "$2a$10$HPFSWUc8A7IYbE0woRrd0eOyX2Oz0k7wD/iaDCCAOZpUIYXk.D90G", remember_digest: nil, admin: false},
  {name: "Maxwell", username: "kofi", email: "kofi@piano.com", bio: "alsdhasdf sadfasdf", expertise: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, password_digest: "$2a$10$VQ43qf7hjYpyBwwuuAT7deo./HsD4t3VFHdc5SaePxNY32OfnYdBy", remember_digest: nil, admin: false},
  {name: "Karla", username: "karla", email: "karlarish@gmail.com", bio: "Chef from Accra", expertise: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, password_digest: "$2a$10$fLUoJIrIL8X.xvACtyk60ed1tL2mMSDpgyWH42/kidS4dXSP1FyAa", remember_digest: nil, admin: nil},
  {name: "Yaw Amponsah", username: "yaw", email: "yaw@kofikrom.com", bio: "I am a fellow at the Meltwater Entrepreneurial School of Technology", expertise: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, password_digest: "$2a$10$uEceQ2qScmZvkSfUZecKOOP9r3W2iaB7zgvmTYOrgU77dei0V46KC", remember_digest: nil, admin: nil}
])
DessertType.create!([
  {name: "Cake Recipes", image_file_name: "57340.jpg", image_content_type: "image/jpeg", image_file_size: 71692, image_updated_at: "2015-11-21 16:23:28"},
  {name: "Candy Recipes", image_file_name: "52801.jpg", image_content_type: "image/jpeg", image_file_size: 82276, image_updated_at: "2015-11-21 16:23:28"},
  {name: "Cobbler Recipes", image_file_name: "60619.jpg", image_content_type: "image/jpeg", image_file_size: 38557, image_updated_at: "2015-11-21 16:23:28"},
  {name: "Cookie Recipes", image_file_name: "54413.jpg", image_content_type: "image/jpeg", image_file_size: 75941, image_updated_at: "2015-11-21 16:23:28"},
  {name: "Crisps and Crumbles Recipes", image_file_name: "55959.jpg", image_content_type: "image/jpeg", image_file_size: 39038, image_updated_at: "2015-11-21 16:23:29"},
  {name: "Custards and Pudding Recipes", image_file_name: "55251.jpg", image_content_type: "image/jpeg", image_file_size: 23472, image_updated_at: "2015-11-21 16:23:29"},
  {name: "Pie Recipes", image_file_name: "pie.jpg", image_content_type: "image/jpeg", image_file_size: 71707, image_updated_at: "2015-11-21 16:23:29"}
])
Recipe.create!([
  {name: "Jules", description: "Something Here", ingredients: "Another Thing here", directions: "sdlasdf asdhfas dfahsdfasd", ratings: nil, author_id: 5, dessert_type_id: nil, image_file_name: "Desserts_Brownie_Bite.jpg", image_content_type: "image/jpeg", image_file_size: 37615, image_updated_at: "2015-11-21 16:11:03"},
  {name: "Sugar Coated Bitter Pill", description: "Prepare this meal at your own risk", ingredients: "Any bitter ingredient of your choice is cool", directions: "Lets do it", ratings: nil, author_id: 5, dessert_type_id: nil, image_file_name: "55959.jpg", image_content_type: "image/jpeg", image_file_size: 39038, image_updated_at: "2015-11-21 16:11:04"},
  {name: "Cranberry Upside-Down Sour Cream Cake", description: "\"I received this recipe a couple of years ago from a friend and get rave reviews from everyone each time I prepare it. It is not only delicious, but very pretty for a holiday table. Great for Thanksgiving or Christmas.\"", ingredients: "1/2 cup butter\r\n2 cups white sugar\r\n2 tablespoons water\r\n1 teaspoon ground cinnamon\r\n1 (12 ounce) bag fresh or frozen cranberries\r\n1 1/2 cups cake flour\r\n1/2 teaspoon baking soda", directions: "Preheat the oven to 350 degrees F (175 degrees C). Generously grease a 9 inch springform pan. Wrap aluminum foil around the outside of the bottom to prevent leaking.\r\n\r\nMelt the butter in a saucepan over medium heat. Stir in 1 1/2 cups of white sugar, water and cinnamon until sugar has dissolved. Bring to a boil and then add the cranberries. Stir to coat with the sauce, then pour into the prepared pan.\r\n\r\nSift together the flour, baking soda and salt; set aside. In a medium bowl, beat the remaining 6 tablespoons of butter with 1/2 cup white sugar and brown sugar until light and fluffy. Mix in the eggs one at a time, beating well after each addition. Stir in vanilla and sour cream. Mix in the dry ingredients. Pour the batter over the cranberries in the pan.\r\n\r\nBake for about 50 minutes in the preheated oven, or until a knife inserted into the center comes out clean. Cool on a rack for 10 minutes, then run a knife around the outer edge. Invert onto a serving plate and remove the springform pan.", ratings: nil, author_id: 2, dessert_type_id: 5, image_file_name: "cranberry_cake_recipe.jpg", image_content_type: "image/jpeg", image_file_size: 114707, image_updated_at: "2015-11-21 16:11:04"},
  {name: "Fish Bowl", description: "ashldfasd fasdhfasd f", ingredients: "alkshdfas dfas dfa sdfh", directions: "asd falhsdf asdhfas df", ratings: nil, author_id: 3, dessert_type_id: 8, image_file_name: "60619.jpg", image_content_type: "image/jpeg", image_file_size: 38557, image_updated_at: "2015-11-26 08:36:01"},
  {name: "early morning starters", description: "Single layer cake", ingredients: "flour, eggs, vanilla ice cream, butter, raisins, cream", directions: "mix 2 eggs into a 100gm flour. Add butter and cream", ratings: nil, author_id: 6, dessert_type_id: 5, image_file_name: "dessert.jpg", image_content_type: "image/jpeg", image_file_size: 31582, image_updated_at: "2015-11-26 12:52:57"},
  {name: "Mary Sobolo", description: "It is one from Meltwater", ingredients: "sugar, milk", directions: "something here", ratings: nil, author_id: 7, dessert_type_id: 6, image_file_name: "mary_cake.jpg", image_content_type: "image/jpeg", image_file_size: 251327, image_updated_at: "2015-11-26 13:19:34"}
])
